index.html
Regarding the issue 'Apple Web App'. You might want to remove / change the status bar style that I've added accidentally. :+1:
=> Enhancement: Apple Web App

gulpfile.js, package.json
Fixed the `mkdir -p dist` bug in issue #802.
=> fixed bug mkdir -p bug #802

index.html
Merge changes made to index.html in 'master' to 'gh-pages' for the 'master' branch still has not been merged with the 'gh-pages' branch.
=> Improvement: Apple Web App (update gh-pages)

app/collections/files.js, test/fixtures/metadata.js, test/index.js, test/spec/collections/files.js
=> Re-implement CURRENT_DATETIME replacement in metadata

CONTRIBUTING.md
Hopefully this saves some time to the next bug hunter
=> Add note on what to do if debugger gets confused

translations/locales/es.json
Some additional translations in spanish for the metadata/file screens
=> A few useful spanish string translations

test/index.html
@dereklieu Not sure if this is quite the right place to fix this, but it works.
=> Fix for 'global leak' error #856

app/views/metadata.js, test/spec/views/metadata.js
Fixes https://github.com/prose/prose/issues/877
=> Fix #877: multiple hidden elements were not forming in frontmatter

style.css
Really basic update to address #819.
=> Add min/max width to container to make editor more fluid

app/views/meta/textarea.js, test/spec/views/meta-forms.js
Close #937 h/t @andrew-luminal
=> Textarea meta elements do not endlessly escape

gulpfile.js, package.json, style.css, style/_codemirror.scss, style/_font.scss, style/_main.scss, style/_reset.scss, style/_responsive.scss, style/_type.scss, style/style.scss
=> Decouple css

app/views/toolbar.js, templates/toolbar.html
@dereklieu: This PR addresses #879.
=> Update toolbar html & add methods to modify lists on icon click

.build_scripts/deploy.sh, app/views/meta/multiselect.js, app/views/meta/select.js, package.json, templates/meta/select.html, test/spec/views/meta-forms.js
=> Metadata selects, multi-selects

app/views/metadata.js, test/spec/views/metadata.js
=> Hidden metadata sets default value of empty string

DEPLOYMENT.md, README.md
Make it easier to find out what Gatekeeper is.
=> Add some gatekeeper reference

app/collections/orgs.js, app/cookie.js, style/_main.scss, style/_responsive.scss, test/index.js, test/spec/collections/orgs.js
Use the authorized user endpoint to show organizations when possible (#826)
Fix #948
=> Organization endpoint

test/index.js, test/spec/vendor/js-yaml.js
=> Confirm quote behavior around booleans in js-yaml

package.json
The major issue this resolves is proper yaml multi-line textarea fields. When filling out a textarea with this content:
**Before:**
```yaml
text_area_test: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore\n\neu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
```
**After:**
```yaml
petition_copy: >-
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim …
```
=> js-yaml to current version

app/collections/orgs.js
=> Set public org access when using public repos

app/router.js
Refactors `router.js` to use the repo-finding logic that accounts for login as well as repo name from [`01fb417`](https://github.com/prose/prose/pull/943/commits/01fb4175dd3eefa0c8a79e5aabcb3259f356321d) and uses it throughout.
Fix #947
=> Consider login when searching for repo

app/views/search.js
Currently search is case sensitive
this PR allows the filtering to be caseinsenstive
=> #989- Make search case insensitive 

.build_scripts/deploy.sh
=> Deploy translation files

app/models/user.js
=> Don't use regex to parse url

app/collections/files.js, app/models/file.js, app/views/file.js, app/views/sidebar/save.js, translations/application.yaml
=> change git commit messages from past to present tense

translations/application.yaml
=> Add description of dot needed after numbers for numbered lists

translations/application.yaml
=> fix link to "Prose contributing guidelines"

app/views/meta/multiselect.js, app/views/meta/select.js, templates/meta/multiselect.html, templates/meta/select.html, test/spec/views/meta-forms.js
=> Allows default values for select and multiselect elements

app/collections/files.js
=> Check for string before running String.replace

app/models/file.js, app/views/header.js, test/spec/models/file.js
=> Use path module

app/models/repo.js
=> Log the repo's url function

gulpfile.js, test/spec/models/file.js
=> Test failure for #1065

translations/locales/es.json
* Minor fixes
* Fixed translation on line 132
* fixed typos on lines 180 & 181
=> Translated word on line 101

README.md
Some blog post are referenced in the readme.md but aren't currently available, I've linked the web archive wayback links to restore the content.
=> 🩹Fix of broken links

.github/workflows/deploy.yml, gulpfile.js, package-lock.json, package.json, yarn.lock
TL;DR: I noticed that deployments have been few and far between likely due to version incompatibility and the use of Travis. I created a workflow that deploys prose to gh-pages using [github actions](https://github.com/features/actions) which will get new versions deployed consistently.
Longer story:
I recently came upon prose and I think it's a great project. I noticed that the docs didn't align with the [live site](https://prose.io/) since the last deploy hasn't happened in over 6 years. After spending sometime getting my own fork running I wanted to share the love and try contributing back to the main project. 
**Changes in summary**
I needed to start by just getting the codebase to build on a modern version of node (I'm using v20 LTS) <br>
Most notable among these is gulp (migrating …
=> Modernize for deployment via actions
