prose/prose

app/router.js, app/views/nav.js, app/views/start.js, style.css, templates/start.html, translations/locales/en.json
Offer unauthenticated users the option to authorize to with GitHub on 404 errors. Redirects back to the original file after successful authentication.
When users try to access a post in a private repository without authorizing first, GitHub's API returns a 404. This gives the user the option to authenticate and return to that page.
=> 404 Authorize button & Repository Scope

app/collections/files.js, test/fixtures/metadata.js, test/spec/collections/files.js, vendor/liquid.patch.js
This PR makes `_config.yml` properties available in the `site` object for previews. I thought this was already happening... it's possible it was overwritten somehow. 
It also includes a minor fix that prevents an error when an included file is empty.
Also, tests seem broken for an unrelated reason.
=> Include _config.yml properties in config object

app/models/file.js, app/models/repo.js
On Chromium 43, editing a file in someone else's repository then saving (which should trigger a fork then a pull request) doesn't work. 
I traced it back to the `collection` argument of the `success` callback of `repo.branches.fetch` being undefined. I only fixed it in a make-it-work-whatever kind of way, reinstating that value from elsewhere—I haven't worked on a Backbone app before and this is as far as I got. (Incidentally, is there a way of interacting with Backbone models of a living app from a command line? I'm used to interactive programming.)
Also, the call:
var branch = collection.findWhere({ name: branch });
...was failing because the `branch` argument was undefined. The in-scope `branch` variable was being shadowed by the newly created `var branch`, and the latter was being …
=> Fix undefined variable and shadowed variable

app/boot.js
This might help contributions: by exposing the Backbone object, it's possible to use the [Chrome Backbone debugger](https://chrome.google.com/webstore/detail/backbone-debugger/bhljhndlimiafopmmhjlgfpnnchjjbhd). (Related: Maluen/Backbone-Debugger#40)
=> Expose Backbone to allow using Backbone debugger

app/collections/files.js
If there are no prose specific settings inside _config.yml or _prose.yml does not exist, then these lines from [app/views/file.js](https://github.com/prose/prose/blob/master/app/views/file.js#L1290-L1293)
```js
// Default to media directory if defined in config,
// current directory if no path specified
var dir = this.config.media ? this.config.media :
util.extractFilename(this.model.get('path'))[0];
```
give a fatal error because `this.config` is not defined.
The [parseConfig()](https://github.com/prose/prose/blob/master/app/collections/files.js#L77) function should at least create an empty config object.
=> Always define the config object

app/views/file.js, app/views/meta/button.js, app/views/meta/checkbox.js, app/views/meta/multiselect.js, app/views/meta/select.js, app/views/meta/text.js, app/views/meta/textarea.js, app/views/metadata.js, gulpfile.js, templates/meta/button.html, test/index.js, test/spec/views/meta-forms.js, test/spec/views/metadata.js
Fixes a number of issues relating to saving and loading metadata from liquid tags.
Includes a major refactor of `app/views/metadata.js`. A big part of this refactor is pushing out the logic of creating, setting, and getting values from form elements into separate views, which are now located in `app/views/meta/`.
Also substantially improves test coverage for the metadata editor and associated form elements. Right now the tests are failing because button form elements I found to be broken, and this fix does not include that (yet) - see #859.
This should address the following tickets:
#836 
#766 
#623 
#582 
Because this is a pretty big refactor, I would love for people to pull this down and test against their own prose configurations, as I continue to test this in the coming days. Please …
=> Metadata fixes

app/views/file.js, test/spec/views/file.js
Currently uploads don't work if config isn't defined, this fixes that in an obtuse way.
Also, extracted (and tested) the defaultPath method.
I'm brand new to the project/codebase so please correct generously. Thanks for your work!
/cc @dereklieu this is what I was working on at Stories LA on Thursday - sorry it took so long. Got distracted by other things.
oh! Also worth noting that 3 tests were failing for me in this PR, but they were also failing in master.
=> check for config before using. Extract defaultPath method

CONTRIBUTING.md, package.json
Instead of requiring users to install `serve` globally and use that command to run a server, this uses the standard command `npm start`. Note that npm recognizes globals for you so serve doesn't have to be installed globally.
Also adds the dev dependency `sinon`, the absence of which was causing the build to fail.
=> Use npm start to abstract serve

app/views/file.js, app/views/sidebar/settings.js, gulpfile.js, index.html, package.json, style.css, templates/file.html, templates/sidebar/settings.html, test/spec/views/file.js, translations/locales/en.json
Adds a spreadsheet editor for CSV files using [handsontable](http://handsontable.com) and [PapaParse](http://papaparse.com).
It's fully functional but I'd still call it a work in progress as I hope to solicit your feedback before recommending a merge. The following items remain:
I welcome your thoughts and feedback!
EDIT: Looks like legacy node builds in travis are failing because handsontable is installed via github (`Unsupported URL Type: github:handsontable/handsontable`). I'm sure there's an easy fix.
=> CSV editor

app/models/file.js
Fixes #916 - unless there was some other reason to insert 2 lines? If so, we can probably just trim a leading `\n` off `content`.
=> Only insert 1 line break after frontmatter

package.json
With this pull request, running `npm start` executes `gulp watch` and `serve` at the same time, so one command to start developing.
It also simplifies the script for `npm test` - [npm scripts](https://docs.npmjs.com/cli/run-script) put any binaries installed by dependencies in the `PATH` when the npm script is run, so it's not necessary to put the full path in there. They'll work even if they're not installed globally.
=> Improve npm scripts

style.css
I've wondered why the metadata editor is so narrow, as it cuts off longer text. This could be resolved with some CSS (though it would need to be CodeMirror-specific) but I thought perhaps a full-width metadata container would be a good idea as well. Thoughts?
Before:
After:
=> Use full width on metadata editor

.gitignore, app/views/meta/textarea.js, app/views/metadata.js, test/spec/views/meta-forms.js, test/spec/views/metadata.js
1. If a metadata form value is not set, and there is no default value, meta forms should* return an empty string `""`.
2. Instead of including the empty string meta value in frontmatter, Prose will now just not include that property.
3. Exceptions are `title` and `published`.
*Textareas forms are another exception, since reading the values are abstracted in CodeMirror and js-yaml code, `"null"` and `"false"` both register as empty strings and thus will not be included. If for some reason you need to set a meta form to `"false"` or `false`, use a text form.
Would close #945
=> Remove unwanted metadata

app/views/file.js
Fixes #959
Note that there is one case where it doesn't recognize the change, which I believe is an issue with Handsontable and have [reported to them](https://github.com/handsontable/handsontable/issues/3465).
=> CSV editor should mark file 'dirty' when col or row is created/removed

CONTRIBUTING.md, package.json
By adding `"postinstall": "gulp"` to package.json, contributors no longer need to have gulp installed globally. added bonus: one fewer step for contributors, same results. 🎉
=> Eliminate global gulp

test/spec/vendor/js-yaml.js
=> New jsyaml wraps quotes in single quotes

app/views/start.js
If a `scope` cookie didn't exist when you authenticated, and you didn't touch the dropdown toggle for public & private/public only, then the app doesn't set a `scope` cookie because `setScope` fires on change events. This should fix that by setting the cookie on init.
=> Save initial scope cookie if public and private

CONTRIBUTING.md
Incrementing version number for every tiny change makes keeping up a [changelog](https://github.com/prose/prose/blob/dont-increment-version/CHANGELOG.md) hard and unwieldy. Deployments are automatic for each push to `master` now, and creating an abundance of versions and tags makes it harder, not easier, to find a specific version of the code.
=> Change semver incrementation to an appeal for tests

app/views/meta/textarea.js
This PR causes two tests to fail, and I'm not totally sure why. 
```
1) Metadata editor view setting defaults on load removes meta values that are empty strings from textarea fields:
AssertionError: expected true to be falsy
2) Metadata form elements Reading values does not endlessly escape text areas:
AssertionError: expected '' to equal '<script>alert("hi");</script>'
+ expected - actual
+<script>alert("hi");</script>
```
attn @dereklieu
=> Resolves colon bug on textareas

app/views/file.js, package.json
Close #1023 
Speeds up diffs on larger files. Previously, Prose would freeze for a few seconds each time you tried to save a moderately large file (~1,500 LOC) as it churned through diffs word-by-word.
=> Diff on lines, rather than words

app/collections/files.js, app/util.js, test/fixtures/metadata.js, test/spec/collections/files.js
Close #557 
Support for automatically inserting the current userid into configuration.
For example, an automatic `author` variable:
prose:
metadata:
"_posts":
- name: "author"
field: "CURRENT_USER"
Or else allow for breaking up the _posts folder by user id:
prose:
rooturl: CURRENT_USER/_posts
media: CURRENT_USER/assets
In case the github login is not what you want, you can also map users. e.g. if I want my personal rooturl to be `alee/_posts`:
prose:
rooturl: CURRENT_USER/_posts
users:
- login: "DevAndyLee"
user: "alee"
This makes for a nicely personalised experience, especially useful for less-technical authors.
=> Implement CURRENT_USER variable in config

app/models/file.js, app/models/repo.js, gulpfile.js, test/spec/models/file.js
This was a dumb mistake I made using nodes `path` module to join urls. The resulting url would look like `https:/something.com` and would get mangled on the reverse proxy redirect. This fixes that and closes #1065.
=> Fix https request path

package.json
Because & is not supported on cmd.exe the solution is to use npm-run-all cli tool
Tested on Windows 10 Pro and CentOs7
=> Making it work on windows

app/util.js, app/views/assetselection.js, app/views/file.js, app/views/meta/image.js, app/views/metadata.js, app/views/toolbar.js, style/_main.scss, style/_type.scss, templates/dialogs/media.html, templates/meta/image.html, templates/toolbar.html, test/spec/views/metadata.js
@dereklieu: Implements issue #998 without using an external service. #998 is an important issue for me and I cannot use prose without this feature.
Usage: 
```
prose:
metadata:
_posts:
- name: "image"
field:
element: "image"
placeholder: "default-image.jpg"
label: "My Image"
```
Possible extension functionality:
Add a _prose.yml config value to allow configuration of it metadata is set equal to the filename, eg `background-homepage.png`, directory, eg `/assets/images/background-homepage.png` or fully qualified, eg `{{ site.baseurl }}/assets/images/background-homepage.png`.
=> Implement metadata image selection

app/views/files.js
Addresses #1121 
The destination was not properly set on folders which were escaped prior to rendering. 
Example:
1. Navigate to [https://prose.io/#Tc-001/Prose-bug-repro/tree/main](https://prose.io/#Tc-001/Prose-bug-repro/tree/main)
2. Click into `folder with spaces`
3. Folder is seemingly blank
4. Navigate to [https://prose.io/#Tc-001/Prose-bug-repro/tree/main/Folder%20with%20spaces](https://prose.io/#Tc-001/Prose-bug-repro/tree/main/Folder%20with%20spaces)
5. Folder is no longer blank
This fix:
- Resolves issue by unescaping URIComponents before navigation when in app.
=> Bugfix: Folders were not properly decoded for naviagtion

.github/workflows/test.yml, gulpfile.js, package-lock.json, package.json, test/spec/collections/files.js, test/spec/collections/orgs.js, test/spec/views/metadata.js
Adding a `test.yml` file to ensure that all PR's build and pass all tests before merging. 
I also had to resolve all failing tests which were mostly caused by security updates to chrome that no longer expose cookies. I've added a simple mock to emulate cookie support.
The image test has been altered since the behavior was changed in #1143
=> Update testing framework to mocha-chrome + add tests on PR

app/models/file.js, app/views/file.js, app/views/metadata.js, app/views/toolbar.js, templates/toolbar.html, test/spec/views/metadata.js
This change aims to resolve #111. While Prose was obviously written with first class support for Jekyll, it shouldn't enforce Jekyll semantics on every yaml frontmatter compatible markdown file. 
Furthermore it seems like Prose was using an outdated or incorrect spec for Jekyll.[ According to the Jekyll docs](https://jekyllrb.com/docs/front-matter/#:~:text=Set%20to%20false%20if%20you%20don%E2%80%99t%20want%20a%20specific%20post%20to%20show%20up%20when%20the%20site%20is%20generated.) the only value for `published` that is parsed is `false`, setting `published` to `true` appears to be duplicative.  
**Changes to functionality**
1. The published button now assumes a default state of that of an "Unpublish" button, as depicted:
This better logically follows the flow of published by default, …
=> Change publish button behavior
